Refactorings and new features.
gesundkrank/mrfoosball pull request #24
Opened 2017-05-08 12:07 UTC by gesundkrank

- Renamed `Tournament` to `TournamentController`
- Introduced the `Tournament` model
- Removed color logic from the teams. Each side will stay with the same color.
- Refactored `matchPage` to rely more on precalculated data than on method calls.
- Introduced `incrementBestOfN` which will only be called on user input
- Introduced `checkForRunningMatch` which ignores the cached tournament (fixes the bug that tournament was loaded from stats).
- Introduced rematch logic on server and client side.
- Implemented `cancelTournament` API endpoint.

2017-05-09 12:26 UTC, hvoecking requested changes

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/app/app.module.ts
> +import { TournamentController } from '../controllers/tournamentController';
Since it is in the `'providers'` why not `TournamentProvider`? I can live with it being called controller though, just asking why

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/controllers/tournamentController.ts
> +import _ from "lodash";
I guess you changed something in this file. If so please do the renaming in a separate commit (that only contains the unavoidable changes like renaming the class name in that commit). Otherwise I can't review what else has changed here

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/models/tournament.ts
> +export class Player {
I like having all the simple data types here :)

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/pages/match/match.html
> +          [color]="'light'"
I decided to go with `left` and `right` since other tables may have different colors

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +import {Match, Team} from "../../models/tournament";
I did not group them together for two reasons. First: you might have to break the line and second: your diffs are not as concise.

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +           })
Why the indenting here? I try to avoid indenting more than the standard indent at a time as much as possible

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +              private readonly tournamentCtrl: TournamentController,) {
This looks ugly IMHO. Why did you choose to do it like this?

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +    this.tournamentCtrl.addGoal(this.teamPositions[color]).then(() => this.update());
I like to put the `then` on a new line, so the instructions that are executed are more visible

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +    if (!this.match) {
Ooops  ^ ^

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +    const [playerA, playerB] = [matchWinner.player1, matchWinner.player2];
Maybe we should decide to consistently use either Characters or Numbers...

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +        switch (finishOption) {
I dislike switch-case since you have to always remember to put a break at the end and can easily introduce bugs that are difficult to spot

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +                                        });
As said before please do not indent this much...

2017-05-09 12:26 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +      .then(() => this.tournamentCtrl.getBestOfN())
This will be so much more readable when changed to async await, not necessary to do it now, but I'm excited :)

2017-05-09 12:26 UTC, hvoecking commented on src/main/java/eu/m6r/kicker/Controller.java
> +            System.out.println(players);
Is this supposed to stay in the code?

2017-05-09 12:27 UTC, gesundkrank commented on frontend/src/app/app.module.ts
> +import { TournamentController } from '../controllers/tournamentController';
No. It's in `controllers`.

2017-05-09 13:03 UTC, gesundkrank commented on src/main/java/eu/m6r/kicker/Controller.java
> +            System.out.println(players);
No 😄

2017-05-09 21:29 UTC, gesundkrank commented on frontend/src/pages/match/match.html
> +          [color]="'light'"
True. But I wanted to simplify things a bit and so I removed that for now.

2017-05-09 21:29 UTC, gesundkrank commented on frontend/src/pages/match/match.ts
> +import {Match, Team} from "../../models/tournament";
Hmm... True. It's the result of the IntelliJ auto-formatting. 😄

2017-05-09 21:30 UTC, gesundkrank commented on frontend/src/pages/match/match.ts
> +           })
Intellij auto-format...

2017-05-09 21:30 UTC, gesundkrank commented on frontend/src/pages/match/match.ts
> +              private readonly tournamentCtrl: TournamentController,) {
intellij ....

2017-05-09 21:31 UTC, gesundkrank commented on frontend/src/pages/match/match.ts
> +    this.tournamentCtrl.addGoal(this.teamPositions[color]).then(() => this.update());
done

2017-05-09 21:32 UTC, gesundkrank commented on frontend/src/pages/match/match.ts
> +    const [playerA, playerB] = [matchWinner.player1, matchWinner.player2];
Yeah. I would use numbers for players and chars for teams. Will change that accordingly.

2017-05-09 21:35 UTC, gesundkrank commented on frontend/src/pages/match/match.ts
> +        switch (finishOption) {
Hmm.. I like it. Especially together with enums.

2017-05-09 21:39 UTC, gesundkrank commented on frontend/src/controllers/tournamentController.ts
> +import _ from "lodash";
done

2017-05-09 21:54 UTC, gesundkrank commented on frontend/src/pages/match/match.ts
> +           })
The indents are based on the opening brackets of the object. Which is IMHO a good in general, but looks weird in this case.

2017-05-09 21:56 UTC, gesundkrank commented
Except for the weird indentions in `@Component` I'm through with the fixups. Would be cool if you could take another look.

2017-05-11 17:21 UTC, hvoecking requested changes

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/controllers/tournamentController.ts
> +        if (team) {
Why should this called without a team name?

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/controllers/tournamentController.ts
> +        if (team) {
Also you can use `Return Home Early` here:
```
if (!team) {
  return;
}
```
Saves you one level of indentation and it is obvious that the processing is done if there is no team, since there can not be an `else` further down the code

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/controllers/tournamentController.ts
> +  getTeamColors(): Promise<{ [key: string]: string }> {
Maybe rename this to `getTeamNames` since it is returning names and not colors

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/controllers/tournamentController.ts
> +    return this.get().then(tournament => ({
how about 
```
_.pick(tournament, ['teamA', 'teamB'])
```

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/controllers/tournamentController.ts
> +      this.recordState();
Shouldn't the state be recorded prior to the change?

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/controllers/tournamentController.ts
> +    const headers = new Headers({'Content-Type': 'application/x-www-form-urlencoded'});
Do you use the slack endpoint here or why are you not sending json?

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/controllers/tournamentController.ts
> +      .then((finished) => {
Why do we need the extra then? :thinking:

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/controllers/tournamentController.ts
> +    let tournament = _.cloneDeep(this.tournament);
Why `let` and not `const`?

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/pages/match/match.html
> +                  {{ rightTeam?.player2.name }}
I first thought it was 
```
rightTeam?.player?.name
```
instead of 
```
rightTeam?.player2.name
```
Maybe `1` and `2` are not the best characters to differentiate the players, since `1` is also easily confused with an `l`
```
player1
```
and
```
playerl
```

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +           })
I really don't think it is "good in general". In this particular case it is very unlikely that the name of `@Component` will change. However, when you have a function name and indent according to its length, then you will have to change the lines of all parameters just because you renamed the function. Is there really no way to tell _intellij_ to not indent it?

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +  private rightWins: number;
Weird, I thought I had made the experience that the template (match.html in this case) would not be able to access private members of MatchPage. However, I might be mistaken or they have changed it in the meantime

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +                        switch (finishOption) {
Indented too far

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +      const alert = this.alertCtrl.create(
The opening brace of the object can be on this line. Would save you one level of indentation

2017-05-11 17:21 UTC, hvoecking commented on frontend/src/pages/stats/stats.ts
> +            setTimeout(function () {
Convert to arrow function

2017-05-18 07:02 UTC, gesundkrank commented on frontend/src/pages/match/match.html
> +                  {{ rightTeam?.player2.name }}
Hmmm... Is that really critical? To stay consistent with the data model I would have to change it accordingly. And the model is leaked up to the database. :worried:

2017-05-18 07:29 UTC, gesundkrank commented on frontend/src/pages/match/match.ts
> +           })
Fixed it.

2017-05-18 07:38 UTC, gesundkrank commented on frontend/src/controllers/tournamentController.ts
> +      this.recordState();
hmmm... I don't know.

2017-05-18 07:42 UTC, gesundkrank commented on frontend/src/controllers/tournamentController.ts
> +    const headers = new Headers({'Content-Type': 'application/x-www-form-urlencoded'});
Was easier to model it in Java this way. Because I didn't need to model it with an object.

https://github.com/mbrtargeting/kicker/blob/refactor/src/main/java/eu/m6r/kicker/api/TournamentAPI.java#L50-L54

2017-05-18 07:42 UTC, gesundkrank commented on frontend/src/controllers/tournamentController.ts
> +      .then((finished) => {
I don't know. Was already there. 😉

2017-05-18 07:45 UTC, gesundkrank commented on frontend/src/pages/match/match.ts
> +                        switch (finishOption) {
Still?

2017-05-18 08:02 UTC, hvoecking requested changes

2017-05-18 08:02 UTC, hvoecking commented on frontend/src/pages/match/match.html
> +                  {{ rightTeam?.player2.name }}
I would say it is definitely worth attacking when we get the chance in the future. But for now it's okay to leave it like this. Maybe I will do it next time I work on the code

2017-05-18 08:02 UTC, hvoecking commented on frontend/src/controllers/tournamentController.ts
> -import * as assert from 'assert';
Could you rename this commit to something a bit more descriptive? Like described in [Commit Messages](https://stroeerdigitalgroup.atlassian.net/wiki/display/MBR/Git+and+Github) ;)

2017-05-18 08:02 UTC, hvoecking commented on frontend/src/controllers/tournamentController.ts
> +      .then((finished) => {
Can you remove it _boy-scout_?

2017-05-18 08:02 UTC, hvoecking commented on frontend/src/pages/match/match.ts
> +                        switch (finishOption) {
Yes, however I saw that your editor unindented it

2017-06-15 14:42 UTC, hvoecking approved these changes

2017-06-15 14:42 UTC, merged