Access queue from frontend
gesundkrank/mrfoosball pull request #80
Opened 2019-04-16 10:34 UTC by lexysoda

2019-04-16 10:36 UTC, lexysoda commented
#69

2019-04-16 10:45 UTC, bratke approved these changes
LGTM

2019-04-16 12:00 UTC, gesundkrank approved these changes
LGTM

2019-04-17 09:33 UTC, gesundkrank requested changes
One minor comment

2019-04-17 09:33 UTC, gesundkrank commented on src/main/java/eu/m6r/kicker/api/TournamentApi.java
> +        } catch (PlayerQueue.PlayerAlreadyInQueueException | PlayerQueue.TooManyUsersException
`PlayerQueue.PlayerAlreadyInQueueException` and `PlayerQueue.TooManyUsersException` should result in something else than a 500. Maybe a 400?

2019-04-18 06:32 UTC, gesundkrank approved these changes

2019-05-06 13:56 UTC, merged